# Generated by Django 5.2.3 on 2025-07-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecar',
            options={'verbose_name': 'ماشین', 'verbose_name_plural': 'ماشین ها'},
        ),
    ]
