# Generated by Django 5.2.3 on 2025-07-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_servicecar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecar',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecar',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
