# Generated by Django 5.2.3 on 2025-07-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_servicecar_city_servicecar_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تعمیر کاران')),
                ('about', models.TextField(verbose_name='درباره ')),
                ('image', models.ImageField(upload_to='about', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'درباره افراد',
            },
        ),
    ]
