# Generated by Django 5.2.3 on 2025-07-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_aboutdrive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(max_length=100, verbose_name='مکان')),
                ('date', models.DateTimeField(verbose_name='زمان تحویل')),
                ('date_map', models.DateTimeField(verbose_name='زمان اتمام')),
            ],
        ),
        migrations.AlterField(
            model_name='servicecar',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='servicecar',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servicecar',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
