# Generated by Django 5.2.3 on 2025-07-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_query_alter_servicecar_link_alter_servicecar_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date',
            field=models.DateField(verbose_name='زمان تحویل'),
        ),
        migrations.AlterField(
            model_name='query',
            name='date_map',
            field=models.DateField(verbose_name='زمان اتمام'),
        ),
    ]
